export * from './catalogos.service';
import { CatalogosService } from './catalogos.service';
export * from './dependencias.service';
import { DependenciasService } from './dependencias.service';
export * from './direcciones.service';
import { DireccionesService } from './direcciones.service';
export * from './reportes.service';
import { ReportesService } from './reportes.service';
export * from './responsables.service';
import { ResponsablesService } from './responsables.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [CatalogosService, DependenciasService, DireccionesService, ReportesService, ResponsablesService, UsuariosService];
