/**
 * BigOp REST API
 * Bienvenido a la documentacion de _BigOp API_._BigOp API_ te permite crear reportes ciudadanos que se canalizaran a las dependencias responsables en un proceso automatico.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joseortiz81@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { DefaultResponse } from '../model/defaultResponse';
import { Incidencia } from '../model/incidencia';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CatalogosService {

    protected basePath = 'https://api.bigop.com/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crea una nueva incidencia.
     * Crea una nueva incidencia.
     * @param body Modelo de la nueva incidencia a ser creada
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addIncidencia(body: Incidencia, observe?: 'body', reportProgress?: boolean): Observable<DefaultResponse>;
    public addIncidencia(body: Incidencia, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DefaultResponse>>;
    public addIncidencia(body: Incidencia, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DefaultResponse>>;
    public addIncidencia(body: Incidencia, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addIncidencia.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DefaultResponse>(`${this.basePath}/catalogos/incidencias`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Edita incidencia.
     * Editar informacion incidencia.
     * @param incidenciaId ID incidencia
     * @param body Modelo de incidencia
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editIncidencia(incidenciaId: number, body: Incidencia, observe?: 'body', reportProgress?: boolean): Observable<DefaultResponse>;
    public editIncidencia(incidenciaId: number, body: Incidencia, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DefaultResponse>>;
    public editIncidencia(incidenciaId: number, body: Incidencia, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DefaultResponse>>;
    public editIncidencia(incidenciaId: number, body: Incidencia, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (incidenciaId === null || incidenciaId === undefined) {
            throw new Error('Required parameter incidenciaId was null or undefined when calling editIncidencia.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editIncidencia.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<DefaultResponse>(`${this.basePath}/catalogos/incidencias/${encodeURIComponent(String(incidenciaId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lista incidencias por responsable
     * Lista incidencias por responsable.
     * @param responsableId ID del responsable
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllIncidenciasByResponsable(responsableId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Incidencia>>;
    public getAllIncidenciasByResponsable(responsableId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Incidencia>>>;
    public getAllIncidenciasByResponsable(responsableId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Incidencia>>>;
    public getAllIncidenciasByResponsable(responsableId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (responsableId === null || responsableId === undefined) {
            throw new Error('Required parameter responsableId was null or undefined when calling getAllIncidenciasByResponsable.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Incidencia>>(`${this.basePath}/catalogos/incidencias/list/${encodeURIComponent(String(responsableId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Informacion incidencia
     * Informacion incidencia.
     * @param incidenciaId ID de la incidencia
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncidenciasById(incidenciaId: number, observe?: 'body', reportProgress?: boolean): Observable<Incidencia>;
    public getIncidenciasById(incidenciaId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Incidencia>>;
    public getIncidenciasById(incidenciaId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Incidencia>>;
    public getIncidenciasById(incidenciaId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (incidenciaId === null || incidenciaId === undefined) {
            throw new Error('Required parameter incidenciaId was null or undefined when calling getIncidenciasById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Incidencia>(`${this.basePath}/catalogos/incidencias/${encodeURIComponent(String(incidenciaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
