/**
 * BigOp REST API
 * Bienvenido a la documentacion de _BigOp API_._BigOp API_ te permite crear reportes ciudadanos que se canalizaran a las dependencias responsables en un proceso automatico.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joseortiz81@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { DefaultResponse } from '../model/defaultResponse';
import { Reporte } from '../model/reporte';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ReportesService {

    protected basePath = 'https://api.bigop.com/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Crea un nuevo reporte.
     * Crea un nuevo reporte.
     * @param body Modelo del nuevo reporte a ser creado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addReporte(body: Reporte, observe?: 'body', reportProgress?: boolean): Observable<DefaultResponse>;
    public addReporte(body: Reporte, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DefaultResponse>>;
    public addReporte(body: Reporte, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DefaultResponse>>;
    public addReporte(body: Reporte, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addReporte.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DefaultResponse>(`${this.basePath}/reportes`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Edita reporte.
     * Editar informacion reporte.
     * @param reporteId ID reporte
     * @param body Modelo del reporte
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editReporte(reporteId: number, body: Reporte, observe?: 'body', reportProgress?: boolean): Observable<DefaultResponse>;
    public editReporte(reporteId: number, body: Reporte, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DefaultResponse>>;
    public editReporte(reporteId: number, body: Reporte, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DefaultResponse>>;
    public editReporte(reporteId: number, body: Reporte, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (reporteId === null || reporteId === undefined) {
            throw new Error('Required parameter reporteId was null or undefined when calling editReporte.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editReporte.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<DefaultResponse>(`${this.basePath}/reportes/${encodeURIComponent(String(reporteId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lista reportes por direccion
     * Lista reportes por direccion.
     * @param direccionId ID de la direccion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllReportesByDireccion(direccionId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Reporte>>;
    public getAllReportesByDireccion(direccionId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Reporte>>>;
    public getAllReportesByDireccion(direccionId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Reporte>>>;
    public getAllReportesByDireccion(direccionId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (direccionId === null || direccionId === undefined) {
            throw new Error('Required parameter direccionId was null or undefined when calling getAllReportesByDireccion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Reporte>>(`${this.basePath}/reportes/list/${encodeURIComponent(String(direccionId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Informacion del reporte
     * Informacion del reporte.
     * @param reporteId ID del reporte
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getReporteById(reporteId: number, observe?: 'body', reportProgress?: boolean): Observable<Reporte>;
    public getReporteById(reporteId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Reporte>>;
    public getReporteById(reporteId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Reporte>>;
    public getReporteById(reporteId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (reporteId === null || reporteId === undefined) {
            throw new Error('Required parameter reporteId was null or undefined when calling getReporteById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Reporte>(`${this.basePath}/reportes/${encodeURIComponent(String(reporteId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
